// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ngbuewhihzcgoczqshwu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5nYnVld2hpaHpjZ29jenFzaHd1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwODQyMjEsImV4cCI6MjA2OTY2MDIyMX0.g4afYLMDCvdwPK6uoY5Xu3ttUOCfSLCsEhr2WfyJAnE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});